/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.form.musterija;

import domain.Musterija;
import domain.TipMusterije;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import ui.controller.ClientController;

/**
 *
 * @author Sreja
 */
public class MusterijaForma extends javax.swing.JFrame {

    private Musterija musterija;
    private PretraziMusterijuForma pmf;

    public PretraziMusterijuForma getPmf() {
        return pmf;
    }

    public void setPmf(PretraziMusterijuForma pmf) {
        this.pmf = pmf;
    }

    /**
     * Creates new form FrizerForma
     */
    public MusterijaForma() throws Exception {
        initComponents();
        popuniComboBoxTipovimaMusterija();
        setLocationRelativeTo(null);
    }

    public Musterija getMusterija() {
        return musterija;
    }

    public void setMusterija(Musterija musterija) {
        this.musterija = musterija;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonKreiraj = new javax.swing.JButton();
        jButtonZapamti = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldTelefon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxTipMusterije = new javax.swing.JComboBox<>();
        jTextFieldPrezime = new javax.swing.JTextField();
        jButtonObrisi = new javax.swing.JButton();
        jButtonOtkazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonKreiraj.setText("Kreiraj");
        jButtonKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKreirajActionPerformed(evt);
            }
        });

        jButtonZapamti.setText("Zapamti");
        jButtonZapamti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZapamtiActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Email");

        jLabel4.setText("Telefon");

        jLabel5.setText("Tip musterije");

        jLabel1.setText("Ime");

        jLabel2.setText("Prezime");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxTipMusterije, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(jTextFieldPrezime)
                            .addComponent(jTextFieldTelefon)
                            .addComponent(jTextFieldIme))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxTipMusterije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jButtonObrisi.setText("Obrisi");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        jButtonOtkazi.setText("Otkazi");
        jButtonOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOtkaziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonOtkazi)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButtonKreiraj)
                        .addGap(44, 44, 44)
                        .addComponent(jButtonZapamti)
                        .addGap(44, 44, 44)
                        .addComponent(jButtonObrisi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonZapamti)
                    .addComponent(jButtonKreiraj)
                    .addComponent(jButtonObrisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButtonOtkazi)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKreirajActionPerformed
        try {
            musterija = ClientController.getInstance().kreirajMusterija();
            JOptionPane.showMessageDialog(this, "Sistem je kreirao musteriju!", "Obavestenje!", JOptionPane.INFORMATION_MESSAGE);
            omoguciPolja();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da kreira musteriju!", "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonKreirajActionPerformed

    private void jButtonZapamtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZapamtiActionPerformed
        try {
            if (jTextFieldIme.getText().equals("") || jTextFieldPrezime.getText().equals("") || jTextFieldEmail.getText().equals("")
                    || jTextFieldTelefon.getText().equals("") || jComboBoxTipMusterije.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Sva polja moraju biti popunjena!", "Upozorenje!", JOptionPane.WARNING_MESSAGE);
                return;
            }
            musterija.setIme(jTextFieldIme.getText());
            musterija.setPrezime(jTextFieldPrezime.getText());
            musterija.setTelefon(jTextFieldTelefon.getText());
            musterija.setEmail(jTextFieldEmail.getText());
            musterija.setTipMusterije((TipMusterije) jComboBoxTipMusterije.getSelectedItem());
            ClientController.getInstance().promeniMusterija(musterija);
            if (pmf != null) {
                pmf.popuniTabeluMusterije();
            }
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio musteriju!", "Obavestenje!", JOptionPane.INFORMATION_MESSAGE);
            if (jButtonKreiraj.isVisible()) {
                isprazniPolja();
                onemoguciPolja();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti musteriju!", "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonZapamtiActionPerformed

    private void jButtonOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOtkaziActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonOtkaziActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        try {
            ClientController.getInstance().obrisiMusteriju(musterija);
            pmf.popuniTabeluMusterije();
            JOptionPane.showMessageDialog(this, "Sistem je obrisao musteriju!", "Obavestenje!", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise musteriju!", "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonObrisiActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonKreiraj;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonOtkazi;
    private javax.swing.JButton jButtonZapamti;
    private javax.swing.JComboBox<Object> jComboBoxTipMusterije;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldPrezime;
    private javax.swing.JTextField jTextFieldTelefon;
    // End of variables declaration//GEN-END:variables

    private void popuniComboBoxTipovimaMusterija() throws Exception {
        List<TipMusterije> tipoviMusterija = ClientController.getInstance().vratiListuSviTipMusterije();
        jComboBoxTipMusterije.setModel(new DefaultComboBoxModel<>(tipoviMusterija.toArray()));
        jComboBoxTipMusterije.setSelectedItem(null);
    }

    public void onemoguciPolja() {
        jTextFieldIme.setEnabled(false);
        jTextFieldPrezime.setEnabled(false);
        jTextFieldEmail.setEnabled(false);
        jTextFieldTelefon.setEnabled(false);
        jComboBoxTipMusterije.setEnabled(false);
        jButtonZapamti.setEnabled(false);
        jButtonKreiraj.setEnabled(true);
    }

    public void omoguciPolja() {
        jTextFieldIme.setEnabled(true);
        jTextFieldPrezime.setEnabled(true);
        jTextFieldEmail.setEnabled(true);
        jTextFieldTelefon.setEnabled(true);
        jComboBoxTipMusterije.setEnabled(true);
        jButtonZapamti.setEnabled(true);
        jButtonKreiraj.setEnabled(false);
    }

    private void isprazniPolja() {
        jTextFieldIme.setText("");
        jTextFieldPrezime.setText("");
        jTextFieldTelefon.setText("");
        jTextFieldEmail.setText("");
        jComboBoxTipMusterije.setSelectedItem(null);
    }

    public void kreairanje() {
        jButtonKreiraj.setVisible(true);
        jButtonZapamti.setVisible(true);
        jButtonObrisi.setVisible(false);
        jButtonKreiraj.setEnabled(true);
        jButtonZapamti.setEnabled(false);
    }

    void detalji() {
        jButtonKreiraj.setVisible(false);
        jButtonZapamti.setVisible(false);
        jButtonObrisi.setVisible(false);
        jTextFieldIme.setEditable(false);
        jTextFieldPrezime.setEditable(false);
        jTextFieldEmail.setEditable(false);
        jTextFieldTelefon.setEditable(false);
        jComboBoxTipMusterije.setEnabled(false);
        jTextFieldIme.setText(musterija.getIme());
        jTextFieldPrezime.setText(musterija.getPrezime());
        jTextFieldEmail.setText(musterija.getEmail());
        jTextFieldTelefon.setText(musterija.getTelefon());
        jComboBoxTipMusterije.setSelectedItem(musterija.getTipMusterije());
    }

    void izmena() {
        jButtonKreiraj.setVisible(false);
        jButtonZapamti.setVisible(true);
        jButtonObrisi.setVisible(false);
        jTextFieldIme.setText(musterija.getIme());
        jTextFieldPrezime.setText(musterija.getPrezime());
        jTextFieldEmail.setText(musterija.getEmail());
        jTextFieldTelefon.setText(musterija.getTelefon());
        jComboBoxTipMusterije.setSelectedItem(musterija.getTipMusterije());
    }

    void brisanje() {
        jButtonKreiraj.setVisible(false);
        jButtonZapamti.setVisible(false);
        jButtonObrisi.setVisible(true);
        jTextFieldIme.setEditable(false);
        jTextFieldPrezime.setEditable(false);
        jTextFieldEmail.setEditable(false);
        jTextFieldTelefon.setEditable(false);
        jComboBoxTipMusterije.setEnabled(false);
        jTextFieldIme.setText(musterija.getIme());
        jTextFieldPrezime.setText(musterija.getPrezime());
        jTextFieldEmail.setText(musterija.getEmail());
        jTextFieldTelefon.setText(musterija.getTelefon());
        jComboBoxTipMusterije.setSelectedItem(musterija.getTipMusterije());
    }
}
