/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.form.musterija;

import domain.Musterija;
import domain.TipMusterije;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modeli.ModelTabeleMusterije;
import ui.controller.ClientController;

/**
 *
 * @author Sreja
 */
public class PretraziMusterijuForma extends javax.swing.JFrame {

    private Musterija musterija;
    private List<Musterija> musterije;

    /**
     * Creates new form PretraziMusterijuForma
     */
    public PretraziMusterijuForma() throws Exception {
        initComponents();
        onemoguciPolja();
        popuniComboBoxTipovimaMusterija();
        popuniTabeluMusterije();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMusterija = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonIme = new javax.swing.JRadioButton();
        jRadioButtonPrezime = new javax.swing.JRadioButton();
        jRadioButtonEmail = new javax.swing.JRadioButton();
        jRadioButtonTelefon = new javax.swing.JRadioButton();
        jRadioButtonTipMusterije = new javax.swing.JRadioButton();
        jLabelIme = new javax.swing.JLabel();
        jLabelPrezime = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelTelefon = new javax.swing.JLabel();
        jLabelTipMusterije = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldPrezime = new javax.swing.JTextField();
        jTextFieldTelefon = new javax.swing.JTextField();
        jComboBoxTipMusterije = new javax.swing.JComboBox<>();
        jButtonPotvrditeKriterijume = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jToggleButtonPretraziMusterije = new javax.swing.JToggleButton();
        jButtonDetaljiMusterije = new javax.swing.JButton();
        jButtonIzmeniMusteriju = new javax.swing.JButton();
        jButtonObrisiMusteriju = new javax.swing.JButton();
        jButtonOtkazi = new javax.swing.JButton();
        jButtonOsveziPolja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableMusterija.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableMusterija);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Pretrazi musterije po:");

        jRadioButtonIme.setText("Ime");

        jRadioButtonPrezime.setText("Prezime");

        jRadioButtonEmail.setText("Email");

        jRadioButtonTelefon.setText("Telefon");
        jRadioButtonTelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTelefonActionPerformed(evt);
            }
        });

        jRadioButtonTipMusterije.setText("Tip musterije");

        jLabelIme.setText("Unesite ime:");

        jLabelPrezime.setText("Unesite prezime:");

        jLabelEmail.setText("Unesite email:");

        jLabelTelefon.setText("Unesite telefon:");

        jLabelTipMusterije.setText("Odaberite tip musterije:");

        jTextFieldTelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefonActionPerformed(evt);
            }
        });

        jButtonPotvrditeKriterijume.setText("Potvrdite kriterijume");
        jButtonPotvrditeKriterijume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPotvrditeKriterijumeActionPerformed(evt);
            }
        });

        jLabel2.setText("Napomena: Ne morate unositi puno ime, prezime, email i telefon vec samo deo.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jButtonPotvrditeKriterijume)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonIme, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButtonPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabelPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(58, 58, 58))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelIme, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonTipMusterije, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButtonTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButtonEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTipMusterije))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxTipMusterije, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldPrezime)
                            .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEmail)
                            .addComponent(jTextFieldTelefon))))
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonPotvrditeKriterijume))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonIme)
                    .addComponent(jLabelIme)
                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelPrezime)
                        .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jRadioButtonPrezime))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonEmail)
                            .addComponent(jLabelEmail))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jTextFieldTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonTelefon)
                            .addComponent(jLabelTelefon))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonTipMusterije)
                            .addComponent(jLabelTipMusterije)
                            .addComponent(jComboBoxTipMusterije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToggleButtonPretraziMusterije.setText("Pretrazi musterije");
        jToggleButtonPretraziMusterije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPretraziMusterijeActionPerformed(evt);
            }
        });

        jButtonDetaljiMusterije.setText("Detalji musterije");
        jButtonDetaljiMusterije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetaljiMusterijeActionPerformed(evt);
            }
        });

        jButtonIzmeniMusteriju.setText("Izmeni musteriju");
        jButtonIzmeniMusteriju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniMusterijuActionPerformed(evt);
            }
        });

        jButtonObrisiMusteriju.setText("Obrisi musteriju");
        jButtonObrisiMusteriju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiMusterijuActionPerformed(evt);
            }
        });

        jButtonOtkazi.setText("Otkazi");
        jButtonOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOtkaziActionPerformed(evt);
            }
        });

        jButtonOsveziPolja.setText("Osvezi polja");
        jButtonOsveziPolja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOsveziPoljaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonOtkazi)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jToggleButtonPretraziMusterije, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonDetaljiMusterije, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonIzmeniMusteriju, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonObrisiMusteriju, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jButtonOsveziPolja)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButtonOsveziPolja)
                        .addGap(69, 69, 69)
                        .addComponent(jToggleButtonPretraziMusterije))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonDetaljiMusterije)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonIzmeniMusteriju)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonObrisiMusteriju))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButtonOtkazi)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonTelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTelefonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonTelefonActionPerformed

    private void jTextFieldTelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonActionPerformed

    private void jButtonPotvrditeKriterijumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPotvrditeKriterijumeActionPerformed
        if (jRadioButtonIme.isSelected()) {
            jLabelIme.setEnabled(true);
            jTextFieldIme.setEnabled(true);
        } else {
            jLabelIme.setEnabled(false);
            jTextFieldIme.setEnabled(false);
        }
        if (jRadioButtonPrezime.isSelected()) {
            jLabelPrezime.setEnabled(true);
            jTextFieldPrezime.setEnabled(true);
        } else {
            jLabelPrezime.setEnabled(false);
            jTextFieldPrezime.setEnabled(false);
        }
        if (jRadioButtonEmail.isSelected()) {
            jLabelEmail.setEnabled(true);
            jTextFieldEmail.setEnabled(true);
        } else {
            jLabelEmail.setEnabled(false);
            jTextFieldEmail.setEnabled(false);
        }
        if (jRadioButtonTelefon.isSelected()) {
            jLabelTelefon.setEnabled(true);
            jTextFieldTelefon.setEnabled(true);
        } else {
            jLabelTelefon.setEnabled(false);
            jTextFieldTelefon.setEnabled(false);
        }
        if (jRadioButtonTipMusterije.isSelected()) {
            jLabelTipMusterije.setEnabled(true);
            jComboBoxTipMusterije.setEnabled(true);
        } else {
            jLabelTipMusterije.setEnabled(false);
            jComboBoxTipMusterije.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonPotvrditeKriterijumeActionPerformed

    private void jToggleButtonPretraziMusterijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPretraziMusterijeActionPerformed
        try {
            musterija = new Musterija();
            if (jTextFieldIme.isEnabled()) {
                if (jTextFieldIme.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Aktivna polja moraju biti popunjena!", "Upozorenje!", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                musterija.setIme(jTextFieldIme.getText());
            }
            if (jTextFieldPrezime.isEnabled()) {
                if (jTextFieldPrezime.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Aktivna polja moraju biti popunjena!", "Upozorenje!", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                musterija.setPrezime(jTextFieldPrezime.getText());
            }
            if (jTextFieldEmail.isEnabled()) {
                if (jTextFieldEmail.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Aktivna polja moraju biti popunjena!", "Upozorenje!", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                musterija.setEmail(jTextFieldEmail.getText());
            }
            if (jTextFieldTelefon.isEnabled()) {
                if (jTextFieldTelefon.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Aktivna polja moraju biti popunjena!", "Upozorenje!", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                musterija.setTelefon(jTextFieldTelefon.getText());
            }
            if (jComboBoxTipMusterije.isEnabled()) {
                if (jComboBoxTipMusterije.getSelectedItem() == null) {
                    JOptionPane.showMessageDialog(this, "Aktivna polja moraju biti popunjena!", "Upozorenje!", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                musterija.setTipMusterije((TipMusterije) jComboBoxTipMusterije.getSelectedItem());
            }
            musterije = ClientController.getInstance().vratiListuMusterija(musterija);
            postaviModelTabeleMusterija();
            if(musterije.isEmpty()){
                throw new Exception();
            }
            JOptionPane.showMessageDialog(this, "Sistem je nasao musterije po zadatim kriterijumima!", "Obavestenje!", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje musterije po zadatim kriterijumima!", "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jToggleButtonPretraziMusterijeActionPerformed

    private void jButtonDetaljiMusterijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetaljiMusterijeActionPerformed
        try {
            int selektovaniRed = jTableMusterija.getSelectedRow();
            if (selektovaniRed == -1) {
                JOptionPane.showMessageDialog(this, "Niste odabrali musteriju!", "Upozorenje", JOptionPane.WARNING_MESSAGE);
                return;
            }
            musterija = musterije.get(selektovaniRed);
            musterija = ClientController.getInstance().pretraziMusterija(musterija);
            JOptionPane.showMessageDialog(this, "Sistem je nasao musteriju!", "Obavestenje!", JOptionPane.INFORMATION_MESSAGE);
            MusterijaForma mf = new MusterijaForma();
            mf.setPmf(this);
            mf.setMusterija(musterija);
            mf.detalji();
            mf.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje musteriju!", "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDetaljiMusterijeActionPerformed

    private void jButtonIzmeniMusterijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniMusterijuActionPerformed
        try {
            int selektovaniRed = jTableMusterija.getSelectedRow();
            if (selektovaniRed == -1) {
                JOptionPane.showMessageDialog(this, "Niste odabrali musteriju!", "Upozorenje", JOptionPane.WARNING_MESSAGE);
                return;
            }
            musterija = musterije.get(selektovaniRed);
            musterija = ClientController.getInstance().pretraziMusterija(musterija);
            JOptionPane.showMessageDialog(this, "Sistem je nasao musteriju!", "Obavestenje!", JOptionPane.INFORMATION_MESSAGE);
            MusterijaForma mf = new MusterijaForma();
            mf.setMusterija(musterija);
            mf.setPmf(this);
            mf.izmena();
            mf.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje musteriju!", "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonIzmeniMusterijuActionPerformed

    private void jButtonObrisiMusterijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiMusterijuActionPerformed
        try {
            int selektovaniRed = jTableMusterija.getSelectedRow();
            if (selektovaniRed == -1) {
                JOptionPane.showMessageDialog(this, "Niste odabrali musteriju!", "Upozorenje", JOptionPane.WARNING_MESSAGE);
                return;
            }
            musterija = musterije.get(selektovaniRed);
            musterija = ClientController.getInstance().pretraziMusterija(musterija);
            JOptionPane.showMessageDialog(this, "Sistem je nasao musteriju!", "Obavestenje!", JOptionPane.INFORMATION_MESSAGE);
            MusterijaForma mf = new MusterijaForma();
            mf.setMusterija(musterija);
            mf.brisanje();
            mf.setPmf(this);
            mf.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje musteriju!", "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonObrisiMusterijuActionPerformed

    private void jButtonOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOtkaziActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonOtkaziActionPerformed

    private void jButtonOsveziPoljaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOsveziPoljaActionPerformed
        try {
            jRadioButtonIme.setSelected(false);
            jRadioButtonPrezime.setSelected(false);
            jRadioButtonEmail.setSelected(false);
            jRadioButtonTelefon.setSelected(false);
            jRadioButtonTipMusterije.setSelected(false);
            jLabelIme.setEnabled(false);
            jLabelPrezime.setEnabled(false);
            jLabelEmail.setEnabled(false);
            jLabelTelefon.setEnabled(false);
            jLabelTipMusterije.setEnabled(false);
            jTextFieldIme.setEnabled(false);
            jTextFieldPrezime.setEnabled(false);
            jTextFieldEmail.setEnabled(false);
            jTextFieldTelefon.setEnabled(false);
            jComboBoxTipMusterije.setEnabled(false);
            jTextFieldIme.setText("");
            jTextFieldPrezime.setText("");
            jTextFieldEmail.setText("");
            jTextFieldTelefon.setText("");
            jComboBoxTipMusterije.setSelectedItem(null);
            popuniTabeluMusterije();
        } catch (Exception ex) {
            Logger.getLogger(PretraziMusterijuForma.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButtonOsveziPoljaActionPerformed

    private void onemoguciPolja() {
        jLabelIme.setEnabled(false);
        jTextFieldIme.setEnabled(false);
        jLabelPrezime.setEnabled(false);
        jTextFieldPrezime.setEnabled(false);
        jLabelEmail.setEnabled(false);
        jTextFieldEmail.setEnabled(false);
        jLabelTelefon.setEnabled(false);
        jTextFieldTelefon.setEnabled(false);
        jLabelTipMusterije.setEnabled(false);
        jComboBoxTipMusterije.setEnabled(false);
    }

    private void popuniComboBoxTipovimaMusterija() throws Exception {
        List<TipMusterije> tipoviMusterija = ClientController.getInstance().vratiListuSviTipMusterije();
        jComboBoxTipMusterije.setModel(new DefaultComboBoxModel<>(tipoviMusterija.toArray()));
        jComboBoxTipMusterije.setSelectedItem(null);
    }

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetaljiMusterije;
    private javax.swing.JButton jButtonIzmeniMusteriju;
    private javax.swing.JButton jButtonObrisiMusteriju;
    private javax.swing.JButton jButtonOsveziPolja;
    private javax.swing.JButton jButtonOtkazi;
    private javax.swing.JButton jButtonPotvrditeKriterijume;
    private javax.swing.JComboBox<Object> jComboBoxTipMusterije;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelIme;
    private javax.swing.JLabel jLabelPrezime;
    private javax.swing.JLabel jLabelTelefon;
    private javax.swing.JLabel jLabelTipMusterije;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonEmail;
    private javax.swing.JRadioButton jRadioButtonIme;
    private javax.swing.JRadioButton jRadioButtonPrezime;
    private javax.swing.JRadioButton jRadioButtonTelefon;
    private javax.swing.JRadioButton jRadioButtonTipMusterije;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMusterija;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldPrezime;
    private javax.swing.JTextField jTextFieldTelefon;
    private javax.swing.JToggleButton jToggleButtonPretraziMusterije;
    // End of variables declaration//GEN-END:variables

    public void postaviModelTabeleMusterija() {
        ModelTabeleMusterije mtm = new ModelTabeleMusterije(musterije);
        jTableMusterija.setModel(mtm);
    }

    public void popuniTabeluMusterije() throws Exception {
        musterije = ClientController.getInstance().vratiListuSviMusterija();
        postaviModelTabeleMusterija();
    }

}
