/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.form;

import domain.Frizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import ui.controller.ClientController;
import ui.form.evidencijaTermina.EvidencijaTerminaForma;
import ui.form.evidencijaTermina.PretraziEvidencijuForma;
import ui.form.frizerskiSalon.FrizerskiSalonForma;
import ui.form.musterija.MusterijaForma;
import ui.form.musterija.PretraziMusterijuForma;

/**
 *
 * @author Sreja
 */
public class PocetnaForma extends javax.swing.JFrame {

    private Frizer ulogovaniFrizer;

    public Frizer getUlogovaniFrizer() {
        return ulogovaniFrizer;
    }

    public void setUlogovaniFrizer(Frizer ulogovaniFrizer) {
        this.ulogovaniFrizer = ulogovaniFrizer;
    }

    /**
     * Creates new form PocetnaForma
     */
    public PocetnaForma() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jButtonOdjaviSe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenuFrizerskiSalon = new javax.swing.JMenu();
        jMenuItemUbaciFrizerskiSalon = new javax.swing.JMenuItem();
        jMenuMusterija = new javax.swing.JMenu();
        jMenuItemKreirajMusterija = new javax.swing.JMenuItem();
        jMenuItemPretraziMusterija = new javax.swing.JMenuItem();
        jMenuEvidencijaTermina = new javax.swing.JMenu();
        jMenuItemKreirajEvidencijaTermina = new javax.swing.JMenuItem();
        jMenuItemPretraziEvidencijaTermina = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenuItem2.setText("jMenuItem2");

        jMenuItem8.setText("jMenuItem8");

        jMenuItem9.setText("jMenuItem9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonOdjaviSe.setText("Odjavi se");
        jButtonOdjaviSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdjaviSeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Dobro dosli!");

        jMenuFrizerskiSalon.setText("Frizerski salon");

        jMenuItemUbaciFrizerskiSalon.setText("Ubaci frizerski salon");
        jMenuItemUbaciFrizerskiSalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUbaciFrizerskiSalonActionPerformed(evt);
            }
        });
        jMenuFrizerskiSalon.add(jMenuItemUbaciFrizerskiSalon);

        jMenuBar2.add(jMenuFrizerskiSalon);

        jMenuMusterija.setText("Musterija");

        jMenuItemKreirajMusterija.setText("Kreiraj musterija");
        jMenuItemKreirajMusterija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKreirajMusterijaActionPerformed(evt);
            }
        });
        jMenuMusterija.add(jMenuItemKreirajMusterija);

        jMenuItemPretraziMusterija.setText("Ptetrazi musterija");
        jMenuItemPretraziMusterija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPretraziMusterijaActionPerformed(evt);
            }
        });
        jMenuMusterija.add(jMenuItemPretraziMusterija);

        jMenuBar2.add(jMenuMusterija);

        jMenuEvidencijaTermina.setText("Evidencija termina");

        jMenuItemKreirajEvidencijaTermina.setText("Kreiraj evidencija termina");
        jMenuItemKreirajEvidencijaTermina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKreirajEvidencijaTerminaActionPerformed(evt);
            }
        });
        jMenuEvidencijaTermina.add(jMenuItemKreirajEvidencijaTermina);

        jMenuItemPretraziEvidencijaTermina.setText("Pretrazi evidencija termina");
        jMenuItemPretraziEvidencijaTermina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPretraziEvidencijaTerminaActionPerformed(evt);
            }
        });
        jMenuEvidencijaTermina.add(jMenuItemPretraziEvidencijaTermina);

        jMenuBar2.add(jMenuEvidencijaTermina);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonOdjaviSe)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(81, 81, 81)
                .addComponent(jButtonOdjaviSe)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemKreirajMusterijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKreirajMusterijaActionPerformed
        try {
            MusterijaForma mf = new MusterijaForma();
            mf.onemoguciPolja();
            mf.kreairanje();
            mf.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(PocetnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemKreirajMusterijaActionPerformed

    private void jMenuItemPretraziMusterijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPretraziMusterijaActionPerformed
        try {
            PretraziMusterijuForma pmf = new PretraziMusterijuForma();
            pmf.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(PocetnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemPretraziMusterijaActionPerformed

    private void jMenuItemKreirajEvidencijaTerminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKreirajEvidencijaTerminaActionPerformed
        try {
            EvidencijaTerminaForma etf = new EvidencijaTerminaForma();
            etf.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(PocetnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemKreirajEvidencijaTerminaActionPerformed

    private void jMenuItemPretraziEvidencijaTerminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPretraziEvidencijaTerminaActionPerformed
        try {
            PretraziEvidencijuForma pef = new PretraziEvidencijuForma();
            pef.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(PocetnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemPretraziEvidencijaTerminaActionPerformed

    private void jMenuItemUbaciFrizerskiSalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUbaciFrizerskiSalonActionPerformed
        FrizerskiSalonForma fsf = new FrizerskiSalonForma();
        fsf.setVisible(true);
    }//GEN-LAST:event_jMenuItemUbaciFrizerskiSalonActionPerformed

    private void jButtonOdjaviSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdjaviSeActionPerformed
        try {
            ClientController.getInstance().odjaviFrizer(ulogovaniFrizer);
            JOptionPane.showMessageDialog(this, "Uspesno ste odjavljeni!", "Obavestenje!", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(PocetnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonOdjaviSeActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOdjaviSe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuEvidencijaTermina;
    private javax.swing.JMenu jMenuFrizerskiSalon;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemKreirajEvidencijaTermina;
    private javax.swing.JMenuItem jMenuItemKreirajMusterija;
    private javax.swing.JMenuItem jMenuItemPretraziEvidencijaTermina;
    private javax.swing.JMenuItem jMenuItemPretraziMusterija;
    private javax.swing.JMenuItem jMenuItemUbaciFrizerskiSalon;
    private javax.swing.JMenu jMenuMusterija;
    // End of variables declaration//GEN-END:variables
}
